layout_spectrum: 0
color:
  saturation: 0.8046595
  lightness: 0.3422939
  brandStrength: 0.1362007
  brandColors:
    - '#B3C8C4'
    - '#153B77'
    - '#A4A179'
    - '#A57E03'
    - '#4C2628'
  rhythmicContrast: 0.7401434
typography_spectrum: 0.1182796
name: Kids Zone Day Care
