name: Kids Zone Day Care
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1182796
title: KIDS ZONE DAYCARE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b3744'
    - '#196f8d'
    - '#ffffff'
    - '#0000ff'
    - '#f79c37'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
